pull_request_rules:
  - name: MickeyMoz
    conditions:
      - author=github-actions[bot]
      - files~=(bitrise.yml)
    actions:
      review:
        type: APPROVE
        message: MickeyMoz 💪
      merge:
        method: rebase
        strict: smart