name: Try create a new commit
on:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  main:
    name: "update file"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Commit and push if bitrise.yml changed
      run: |-
        git diff
        git config --global user.email "firefox-test-engineering@mozilla.com"
        git config --global user.name "Firefox Test Engineering"
        git diff --quiet || (git add README && git commit -m "Updated Readme file")
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: update
          title: Update README
          branch: test-pr
