name: Try create a new commit
on:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  main:
    name: "update file"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update AUTHORS
        run: |
          git log --format='%aN <%aE>%n%cN <%cE>' | sort -u > README
      - name: Create Pull Request
        uses: isabelrios/demo-github-actions@v3.5.0
        with:
          commit-message: update authors
          title: Update README
          branch: test-pr
