ame: Create a PR with changes after importing strings
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false 
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run script to import strings
      run: sh ./test-fixtures/import-strings.sh
    - name: Update new strings
      run: |-
        git diff
        git config --global user.email "firefox-test-engineering@mozilla.com"
        git config --global user.name "Firefox Test Engineering"
        git diff --quiet || (git add Blockzilla/*/*.lproj/* Blockzilla/*.lproj/*)
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
      token: ${{ secrets.GITHUB_TOKEN }}
      #branch: automation/sync-strings-${{ steps.fenix-beta-version.outputs.major-beta-version }}
      title: "Strings import DATE"        
      body: "This (automated) PR import string changes"
      labels: needs:review