name: Create a PR rebase
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false 
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Modify carthage 
      run: |
        python ./test-fixtures/update_application_services.py
    - name: Run Script
      run: |
        cd test-fixtures/
        chmod u+x read_tag_test.sh
        echo "version=$(./read_tag_test.sh)" >> $GITHUB_ENV
    - name: Remove file
      run: |
        pwd
        cd test-fixtures/
        [ ! -e newest_tag.txt ] || rm newest_tag.txt
    - name: Script to check if branch exists
      run: |-
        status=$(curl -X GET -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/isabelrios/demo-github-actions/branches | jq -r '.[].name | select(contains("test-as"))')
        echo $status
        if [ -z "$status" ]; then echo "BRANCH_CREATED=false" >> $GITHUB_ENV; else echo "BRANCH_CREATED=true"  >> $GITHUB_ENV;fi
    - name: Script step to try to rebase
      if: env.BRANCH_CREATED == 'true'
      run: |-
        echo "running rebase"
        git branch -r
        git fetch origin
        git fetch &> /dev/null
        diffs=$(git diff master origin/test-as)
        echo $diffs
        if [ -z "$diffs" ] ; then echo "OK" ; else echo "RebaseNeeded=true" >> $GITHUB_ENV ; fi
    - name: Commit carthage changes a-s
      if: ( env.RebaseNeeded == 'true' || env.BRANCH_CREATED == 'false' )
      run: |-
        git diff
        git config --global user.email "firefox-test-engineering@mozilla.com"
        git config --global user.name "Firefox Test Engineering"
        git diff --quiet || (git add Cartfile Cartfile.resolved)
    - name: Create Pull Request
      if: (env.RebaseNeeded == 'true' || env.BRANCH_CREATED == 'false')
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Auto Update Cartfile with latest A-S version found ${{ env.version }}
        author: MickeyMoz <firefox-test-engineering@mozilla.com>
        committer: MickeyMoz <firefox-test-engineering@mozilla.com>
        title: Auto Update Cartfile ${{ env.version }}
        branch: test-as
        labels: Do Not Merge ⛔️
        token: ${{ secrets.GITHUB_TOKEN }}
